# -*- coding: utf-8 -*-
"""1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17Nuc_hFcnDCpUrVu_v8q2_Ao2KwyE98I
"""

import pandas as pd
import numpy as np
from scipy.stats import mode
import zipfile

# Path to the zip file
zip_path = '/content/HousePrice India.csv.zip'

# Unzipping the file
with zipfile.ZipFile(zip_path, 'r') as zip_ref:
    zip_ref.extractall('/content')

# Assuming the extracted file is named 'House Price India.csv'
csv_path = '/content/HousePrice India.csv'

# Reading data from the CSV file
df = pd.read_csv(csv_path)

# Display original DataFrame with missing values
print("Original DataFrame:")
print(df.head())

# Mean Imputation
mean_value = df['Price'].mean()
df['HousePrice_Mean'] = df['Price'].fillna(mean_value)

# Median Imputation
median_value = df['Price'].median()
df['HousePrice_Median'] = df['Price'].fillna(median_value)

# Mode Imputation
mode_result = mode(df['Price'], nan_policy='omit') # Calculate the mode
if mode_result.mode.size > 0: # Check if a mode was found
    mode_value = mode_result.mode # Extract the mode value directly
    df['HousePrice_Mode'] = df['Price'].fillna(mode_value)
else:
    print("No mode found for 'Price' column.") # Handle the case where no mode is found

# Display DataFrame after imputation
print("\nDataFrame after Imputation:")
print(df.head())

