# -*- coding: utf-8 -*-
"""3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19EkRhj3dy1aOXZSMUEh08ArjsmGLbB7I
"""

import pandas as pd
import numpy as np
from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import IterativeImputer
from sklearn.ensemble import RandomForestRegressor
import zipfile

# Path to the zip file
zip_path = '/content/HousePrice India.csv.zip'

# Unzipping the file
with zipfile.ZipFile(zip_path, 'r') as zip_ref:
    zip_ref.extractall('/content')

# Assuming the extracted file is named 'HousePrice India.csv'
csv_path = '/content/HousePrice India.csv'

# Reading data from the CSV file
df = pd.read_csv(csv_path)

# Display original DataFrame with missing values
print("Original DataFrame:")
print(df.head())

# Selecting the column for imputation
house_prices = df[['Price']]

# Initializing Iterative Imputer with Random Forest Regressor
imputer = IterativeImputer(estimator=RandomForestRegressor(), max_iter=10, random_state=0)

# Applying Random Forest imputation
df['HousePrice_RF'] = imputer.fit_transform(house_prices)

# Display DataFrame after Random Forest imputation
print("\nDataFrame after Random Forest Imputation:")
print(df.head())

