# -*- coding: utf-8 -*-
"""5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11AJr2qWSM_gZJ027ra-1bHa9opGgXs3B
"""

import pandas as pd
import numpy as np
from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import IterativeImputer
from sklearn.linear_model import LinearRegression
import zipfile

# Path to the zip file
zip_path = '/content/HousePrice India.csv.zip'

# Unzipping the file
with zipfile.ZipFile(zip_path, 'r') as zip_ref:
    zip_ref.extractall('/content')

# Assuming the extracted file is named 'HousePrice India.csv'
csv_path = '/content/HousePrice India.csv'

# Reading data from the CSV file
df = pd.read_csv(csv_path)

# Display original DataFrame with missing values
print("Original DataFrame:")
print(df.head())

# Selecting the column for imputation
house_prices = df[['Price']]

# Initializing Iterative Imputer with Linear Regression as the estimator
imputer = IterativeImputer(estimator=LinearRegression(), max_iter=10, random_state=0)

# Applying Regression imputation
df['HousePrice_Regression'] = imputer.fit_transform(house_prices)

# Display DataFrame after Regression imputation
print("\nDataFrame after Regression Imputation:")
print(df.head())

